// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// Runs one SELECT against the aggregator's duck-store. The API renders the
// SQL with the same builder it uses for ClickHouse.
type StatshouseStoreQuery struct {
	FieldsMask uint32
	Sql        string
}

func (StatshouseStoreQuery) TLName() string { return "statshouse.storeQuery" }
func (StatshouseStoreQuery) TLTag() uint32  { return 0x57cb1011 }

func (item *StatshouseStoreQuery) Reset() {
	item.FieldsMask = 0
	item.Sql = ""
}

func (item *StatshouseStoreQuery) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomUint(rg)
	item.Sql = basictl.RandomString(rg)
}

func (item *StatshouseStoreQuery) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	return basictl.StringRead(w, &item.Sql)
}

func (item *StatshouseStoreQuery) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQuery) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.StringWrite(w, item.Sql)
	return w
}

func (item *StatshouseStoreQuery) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1011); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQuery) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQuery) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1011)
	return item.WriteTL1(w)
}

func (item *StatshouseStoreQuery) ReadResultTL1(w []byte, ret *StatshouseStoreQueryResponse) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseStoreQuery) WriteResultTL1(w []byte, ret StatshouseStoreQueryResponse) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseStoreQuery) ReadResultJSON(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, ret *StatshouseStoreQueryResponse) error {
	if err := ret.ReadJSONGeneral(jctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseStoreQuery) WriteResultJSON(w []byte, ret StatshouseStoreQueryResponse) (_ []byte, err error) {
	return item.writeResultJSON(nil, w, ret)
}

func (item *StatshouseStoreQuery) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret StatshouseStoreQueryResponse) (_ []byte, err error) {
	w = ret.WriteJSONOpt(jctx, w)
	return w, nil
}

func (item *StatshouseStoreQuery) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseStoreQueryResponse
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseStoreQuery) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreQueryResponse
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(jctx, w, ret)
	return r, w, err
}

func (item *StatshouseStoreQuery) ReadResultJSONWriteResultTL1(jctx *basictl.JSONReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreQueryResponse
	if err = item.ReadResultJSON(jctx, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseStoreQuery) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

func (item *StatshouseStoreQuery) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

func (item *StatshouseStoreQuery) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

func (item *StatshouseStoreQuery) ReadResultJSONWriteResultTL2(jctx *basictl.JSONReadContext, tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

func (item StatshouseStoreQuery) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQuery) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQuery) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propSqlPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuery", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "sql":
				if propSqlPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuery", "sql")
				}
				propSqlPresented = true
				if err := Json2ReadString(in, &item.Sql); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQuery", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propSqlPresented {
		item.Sql = ""
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQuery) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQuery) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQuery) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexSql := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"sql":`...)
	w = basictl.JSONWriteString(w, item.Sql)
	if !(len(item.Sql) != 0) {
		w = w[:backupIndexSql]
	}
	return append(w, '}')
}

func (item *StatshouseStoreQuery) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQuery) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQuery", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQuery) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQuery"))
}

func (item *StatshouseStoreQuery) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

// Runs one SELECT against the aggregator's duck-store. The API renders the
// SQL with the same builder it uses for ClickHouse.
type StatshouseStoreQueryBytes struct {
	FieldsMask uint32
	Sql        []byte
}

func (StatshouseStoreQueryBytes) TLName() string { return "statshouse.storeQuery" }
func (StatshouseStoreQueryBytes) TLTag() uint32  { return 0x57cb1011 }

func (item *StatshouseStoreQueryBytes) Reset() {
	item.FieldsMask = 0
	item.Sql = item.Sql[:0]
}

func (item *StatshouseStoreQueryBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomUint(rg)
	item.Sql = basictl.RandomStringBytes(rg)
}

func (item *StatshouseStoreQueryBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	return basictl.StringReadBytes(w, &item.Sql)
}

func (item *StatshouseStoreQueryBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQueryBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.StringWriteBytes(w, item.Sql)
	return w
}

func (item *StatshouseStoreQueryBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1011); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQueryBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQueryBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1011)
	return item.WriteTL1(w)
}

func (item *StatshouseStoreQueryBytes) ReadResultTL1(w []byte, ret *StatshouseStoreQueryResponseBytes) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseStoreQueryBytes) WriteResultTL1(w []byte, ret StatshouseStoreQueryResponseBytes) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseStoreQueryBytes) ReadResultJSON(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, ret *StatshouseStoreQueryResponseBytes) error {
	if err := ret.ReadJSONGeneral(jctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseStoreQueryBytes) WriteResultJSON(w []byte, ret StatshouseStoreQueryResponseBytes) (_ []byte, err error) {
	return item.writeResultJSON(nil, w, ret)
}

func (item *StatshouseStoreQueryBytes) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret StatshouseStoreQueryResponseBytes) (_ []byte, err error) {
	w = ret.WriteJSONOpt(jctx, w)
	return w, nil
}

func (item *StatshouseStoreQueryBytes) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseStoreQueryResponseBytes
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseStoreQueryBytes) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreQueryResponseBytes
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(jctx, w, ret)
	return r, w, err
}

func (item *StatshouseStoreQueryBytes) ReadResultJSONWriteResultTL1(jctx *basictl.JSONReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreQueryResponseBytes
	if err = item.ReadResultJSON(jctx, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseStoreQueryBytes) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

func (item *StatshouseStoreQueryBytes) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

func (item *StatshouseStoreQueryBytes) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

func (item *StatshouseStoreQueryBytes) ReadResultJSONWriteResultTL2(jctx *basictl.JSONReadContext, tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}

func (item StatshouseStoreQueryBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQueryBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQueryBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propSqlPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuery", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "sql":
				if propSqlPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuery", "sql")
				}
				propSqlPresented = true
				if err := Json2ReadStringBytes(in, &item.Sql); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQuery", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propSqlPresented {
		item.Sql = item.Sql[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQueryBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQueryBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQueryBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexSql := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"sql":`...)
	w = basictl.JSONWriteStringBytes(w, item.Sql)
	if !(len(item.Sql) != 0) {
		w = w[:backupIndexSql]
	}
	return append(w, '}')
}

func (item *StatshouseStoreQueryBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQueryBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQuery", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQueryBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQuery"))
}

func (item *StatshouseStoreQueryBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQuery")
}
