// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// Result of statshouse.storeQuery: every column of the result set in
// ClickHouse Native encoding, so the API decodes duck-store answers with the
// same column readers it uses for ClickHouse.
type StatshouseStoreQueryResponse struct {
	Rows    int32
	Columns []string
}

func (StatshouseStoreQueryResponse) TLName() string { return "statshouse.storeQueryResponse" }
func (StatshouseStoreQueryResponse) TLTag() uint32  { return 0x57cb1010 }

func (item *StatshouseStoreQueryResponse) Reset() {
	item.Rows = 0
	item.Columns = item.Columns[:0]
}

func (item *StatshouseStoreQueryResponse) FillRandom(rg *basictl.RandGenerator) {
	item.Rows = basictl.RandomInt(rg)
	BuiltinVectorStringFillRandom(rg, &item.Columns)
}

func (item *StatshouseStoreQueryResponse) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.IntRead(w, &item.Rows); err != nil {
		return w, err
	}
	return BuiltinVectorStringReadTL1(w, &item.Columns)
}

func (item *StatshouseStoreQueryResponse) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQueryResponse) WriteTL1(w []byte) []byte {
	w = basictl.IntWrite(w, item.Rows)
	w = BuiltinVectorStringWriteTL1(w, item.Columns)
	return w
}

func (item *StatshouseStoreQueryResponse) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1010); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQueryResponse) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQueryResponse) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1010)
	return item.WriteTL1(w)
}

func (item StatshouseStoreQueryResponse) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQueryResponse) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQueryResponse) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propRowsPresented bool
	var propColumnsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "rows":
				if propRowsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryResponse", "rows")
				}
				propRowsPresented = true
				if err := Json2ReadInt32(in, &item.Rows); err != nil {
					return err
				}
			case "columns":
				if propColumnsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryResponse", "columns")
				}
				propColumnsPresented = true
				if err := BuiltinVectorStringReadJSONGeneral(jctx, in, &item.Columns); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQueryResponse", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propRowsPresented {
		item.Rows = 0
	}
	if !propColumnsPresented {
		item.Columns = item.Columns[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQueryResponse) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQueryResponse) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQueryResponse) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexRows := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"rows":`...)
	w = basictl.JSONWriteInt32(w, item.Rows)
	if !(item.Rows != 0) {
		w = w[:backupIndexRows]
	}
	backupIndexColumns := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"columns":`...)
	w = BuiltinVectorStringWriteJSONOpt(jctx, w, item.Columns)
	if !(len(item.Columns) != 0) {
		w = w[:backupIndexColumns]
	}
	return append(w, '}')
}

func (item *StatshouseStoreQueryResponse) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQueryResponse) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQueryResponse", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQueryResponse) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQueryResponse"))
}

func (item *StatshouseStoreQueryResponse) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQueryResponse")
}

// Result of statshouse.storeQuery: every column of the result set in
// ClickHouse Native encoding, so the API decodes duck-store answers with the
// same column readers it uses for ClickHouse.
type StatshouseStoreQueryResponseBytes struct {
	Rows    int32
	Columns [][]byte
}

func (StatshouseStoreQueryResponseBytes) TLName() string { return "statshouse.storeQueryResponse" }
func (StatshouseStoreQueryResponseBytes) TLTag() uint32  { return 0x57cb1010 }

func (item *StatshouseStoreQueryResponseBytes) Reset() {
	item.Rows = 0
	item.Columns = item.Columns[:0]
}

func (item *StatshouseStoreQueryResponseBytes) FillRandom(rg *basictl.RandGenerator) {
	item.Rows = basictl.RandomInt(rg)
	BuiltinVectorStringBytesFillRandom(rg, &item.Columns)
}

func (item *StatshouseStoreQueryResponseBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.IntRead(w, &item.Rows); err != nil {
		return w, err
	}
	return BuiltinVectorStringBytesReadTL1(w, &item.Columns)
}

func (item *StatshouseStoreQueryResponseBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQueryResponseBytes) WriteTL1(w []byte) []byte {
	w = basictl.IntWrite(w, item.Rows)
	w = BuiltinVectorStringBytesWriteTL1(w, item.Columns)
	return w
}

func (item *StatshouseStoreQueryResponseBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1010); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQueryResponseBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQueryResponseBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1010)
	return item.WriteTL1(w)
}

func (item StatshouseStoreQueryResponseBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQueryResponseBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQueryResponseBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propRowsPresented bool
	var propColumnsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "rows":
				if propRowsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryResponse", "rows")
				}
				propRowsPresented = true
				if err := Json2ReadInt32(in, &item.Rows); err != nil {
					return err
				}
			case "columns":
				if propColumnsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryResponse", "columns")
				}
				propColumnsPresented = true
				if err := BuiltinVectorStringBytesReadJSONGeneral(jctx, in, &item.Columns); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQueryResponse", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propRowsPresented {
		item.Rows = 0
	}
	if !propColumnsPresented {
		item.Columns = item.Columns[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQueryResponseBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQueryResponseBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQueryResponseBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexRows := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"rows":`...)
	w = basictl.JSONWriteInt32(w, item.Rows)
	if !(item.Rows != 0) {
		w = w[:backupIndexRows]
	}
	backupIndexColumns := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"columns":`...)
	w = BuiltinVectorStringBytesWriteJSONOpt(jctx, w, item.Columns)
	if !(len(item.Columns) != 0) {
		w = w[:backupIndexColumns]
	}
	return append(w, '}')
}

func (item *StatshouseStoreQueryResponseBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQueryResponseBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQueryResponse", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQueryResponseBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQueryResponse"))
}

func (item *StatshouseStoreQueryResponseBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQueryResponse")
}
